# docker stack deploy --prune -c elk.yml elk
# docker service logs -f --tail=0 --raw elk_logstash
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - 5601:5601
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    deploy:
      mode: global
    command:
      - -E
      - filebeat.inputs=[{type:docker,containers.ids:*}]
      - -E
      - processors={1:{add_docker_metadata:{host:unix:///var/run/docker.sock}}} 
      - -E
      - output.elasticsearch.enabled=false
      - -E
      - output.logstash.enabled=true
      - -E
      - output.logstash.hosts=["logstash:5044"]
      - -v
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    user: root
    hostname: "{{.Node.Hostname}}"
    command:
      - -E
      - |
        metricbeat.modules=[
          {
            module:docker,
            hosts:[unix:///var/run/docker.sock],
            period:10s,
            enabled:true
          }
        ] 
      - -E
      - processors={1:{add_docker_metadata:{host:unix:///var/run/docker.sock}}} 
      - -E
      - output.elasticsearch.enabled=false
      - -E
      - output.logstash.enabled=true
      - -E
      - output.logstash.hosts=["logstash:5044"]
    deploy:
      mode: global
  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    environment:
      - XPACK_MANAGEMENT_ENABLED=false
    command:
      - -e
      - |
        input { 
          beats { 
            port => 5044
          } 
          gelf { }
        }
        output {
          if [@metadata][beat] {
            elasticsearch {
              hosts => [ "//elasticsearch" ]
              manage_template => false
              index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}" 
            }
          } else {
            elasticsearch {
              hosts => [ "//elasticsearch" ]
              index => "logstash-%{+YYYY.MM.dd}"
            }
          }
        }
volumes:
  elasticsearch-data: {}
