# docker stack deploy --prune -c elk.yml elk
# docker service logs -f --tail=0 --raw elk_logstash
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - 5601:5601
    environment:
      - XPACK_MONITORING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
      - XPACK_GRAPH_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    deploy:
      mode: global
    command:
      - -E
      - output.elasticsearch.enabled=false
      - -E
      - output.logstash.enabled=true
      - -E
      - output.logstash.hosts=["logstash:5044"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command:
      - -E
      - autodiscover.providers=["docker"]
      - -E
      - output.elasticsearch.enabled=false
      - -E
      - output.logstash.enabled=true
      - -E
      - output.logstash.hosts=["logstash:5044"]
      - -v
    deploy:
      mode: global
  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    ports:
      - 5000:5000
    environment:
      - XPACK_MANAGEMENT_ENABLED=false
    command:
      - -e
      - |
        input { 
          beats { 
            port => 5044
          } 
          gelf { }
          tcp {
            port => 5000
          }
        }
        output {
          if [@metadata][beat] {
            elasticsearch {
              hosts => [ "//elasticsearch" ]
              manage_template => false
              index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}" 
            }
          } else {
            elasticsearch {
              hosts => [ "//elasticsearch" ]
              index => "logstash-%{+YYYY.MM.dd}"
            }
          }
        }
volumes:
  elasticsearch-data: {}
